version: '3'
services:
  backend:
    cap_add:
      - SYS_PTRACE
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    volumes:
      - .:/opt/app

    env_file:
      - .env
    environment:
      - FLASK_APP=manage.py
      - FLASK_ENV=development
    command: ./scripts/be_run.sh
    ports:
      - "8080:8080"

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    volumes:
      - ./frontend:/app
      - ./scripts:/scripts/
      - /app/node_modules
    env_file:
      - .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "3000:3000"
    stdin_open: true

  nginx:
    image: nginx
    restart: always
    volumes:
      - ./docker/default.conf:/etc/nginx/conf.d/default.conf
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - backend
